# Default path for the config file:
#   Linux: ~/.config/lazygit/config.yml
#   MacOS: ~/Library/Application\ Support/lazygit/config.yml
#   Windows: %APPDATA%\lazygit\config.yml

# gui:
#     theme:
#         lightTheme: false
#         optionsTextColor:
#             - green
#         unstagedChangesColor:
#             - pink

gui:
    language: 'en'

update:
    method: never

# determines whether hitting 'esc' will quit the application when there is nothing to cancel/close
# quitOnTopLevelReturn: false
# disableStartupPopups: false
notARepository: 'skip'
